### ISSUE TITLE
Support External PostgreSQL Instances

### ISSUE THREAD

**Issue by simon3z** [ManageIQ/manageiq-pods#107]
It should be possible to deploy ManageIQ podified also with an external PostgreSQL instance.

I suppose in this case you wouldn't deploy the regular posgres dc but just configure an endpoint (not even sure you need a service in this case, an endpoint would be enough IIRC) to point to the external PostgreSQL instance (configuration given by the user).

Maybe it should be a different template?

cc @fbladilo @bazulay

**Comment by fbladilo** [comment]
@simon3z Likely to be a separate template as we will not need all of the PG REST objects at all in this case, also necessary logic needs to be implemented to detect/handle the external PG setup, this data will be required by user, along with proper PG role setup on the remote PG in order to create/migrate DB.

**Comment by fbladilo** [comment]
@bazulay Are we Ok to close this one?

**Comment by bazulay** [comment]
Per the merge of #119 
Closing this issue
