### ISSUE TITLE
Use klog for ManageIQ operator

### ISSUE THREAD

**Issue by gyliu513** [ManageIQ/manageiq-pods#461]
@miq-bot add_label bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:**

The current log in the operator is not easy to read:

```
{"level":"info","ts":1587517980.2473092,"logger":"cmd","msg":"Operator Version: 0.0.1"}
{"level":"info","ts":1587517980.2473514,"logger":"cmd","msg":"Go Version: go1.13"}
{"level":"info","ts":1587517980.2473543,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1587517980.2473598,"logger":"cmd","msg":"Version of operator-sdk: v0.15.1"}
{"level":"info","ts":1587517980.2484946,"logger":"leader","msg":"Trying to become the leader."}
{"level":"info","ts":1587517982.6786876,"logger":"leader","msg":"No pre-existing lock was found."}
{"level":"info","ts":1587517982.6859107,"logger":"leader","msg":"Became the leader."}
```

How about migrate to klog?

Comments? @carbonin @Fryguy @chessbyte

**Comment by carbonin** [comment]
What would the klog output look like?

**Comment by gyliu513** [comment]
Format as follows:

```
I0422 10:26:16.893389   23689 reconcile_operand.go:54] Reconciling custom resource: ibm-management-ingress-operator
I0422 10:26:16.893403   23689 reconcile_operand.go:89] Looking for the Cluster Service Version in Subscription: ibm-management-ingress-operator
```

**Comment by carbonin** [comment]
We're shooting for JSON format so that we were compatible with centralized logging solutions.
With JSON each of the log fields will be automatically parsed into elasticsearch and searchable.

Unless we don't expect users to be using centralized logging I would rather stick with JSON.

**Comment by gyliu513** [comment]
@carbonin I can see most kubernetes projects are using klog, even with klog, I think we can still parse the log and push to elasticsearch?

**Comment by carbonin** [comment]
I don't want to be responsible for pushing to elasticsearch, that's exactly the point of centralized logging. The systems that I've used in the past automatically scrape any logs sent to stdout of any container and index them into elastic and make them available in kibana with no work on the part of the application developer aside from printing logs as JSON.

You could make the argument that it's not as important to index operator logs properly because the operator itself will never scale to multiple replicas so it's not as complicated to find the logs you're looking for... But I also don't find the json logs particularly difficult to read.

@Fryguy any thoughts on this? I guess we can move the operator logs to some other logger, but I would prefer to keep the application logs as json as it would be much more difficult to keep track of multiple replicas without a log aggregator.

**Comment by Fryguy** [comment]
I agree with @carbonin 's assessment.  Unless there is some of of built-in tooling where all klog format logs are handled automatically by kubernetes without the user doing anything, then I think we would lose the structured output provided by JSON, which in turn is much easier to consume in log aggregators.

Separately, would it be weird if the operator log is in one format and the rest of the application logs in a different format?  I think if we are going to move to a different log format, we should probably do it across the board.  Again, though, unless there's a built-in kubernetes thing for handling this log format, I think I'd be against this change.

**Comment by Fryguy** [comment]
> The current log in the operator is not easy to read:

Forgot to add, but aren't we using the default logging provided by the operator-sdk?  I assumed that if the operator-sdk picked JSON it was for a reason, like automatic post-processing.

**Comment by gyliu513** [comment]
Seems operator-sdk has some plan to enable klog as default https://github.com/operator-framework/operator-sdk/issues/2887

**Comment by Fryguy** [comment]
> Also, just to clarify we are not planning to switch from zap to klog.

They are not switching to klog, but have provided code examples to enable using klog.

**Comment by carbonin** [comment]
I think we'll stick with the sdk default. Closing this.
