### ISSUE TITLE
Upgrade Postgresql for security fixes and need instructions for customers on how to upgrade their current installation.

### ISSUE THREAD

**Issue by bhadrim** [ManageIQ/manageiq-pods#625]
The Postgresql minor release that gets into the system is based on the build time. The version that is built may have security issues that gets fixed in newer minor release. This enhancement request is to address

1. We need to deliver instructions for customers on how to upgrade their current installation to fix the security issues. (this is applicable to both pod and appliance)

2. We need to rebuild the current images to get the new minor release to address the issues fixed for following CVEs

https://nvd.nist.gov/vuln/detail/CVE-2019-10164 (affects before 10.9)
https://nvd.nist.gov/vuln/detail/CVE-2020-1720 (affects before 10.12)
https://nvd.nist.gov/vuln/detail/CVE-2020-14349 (affects before 10.14)

Note: In one of my appliance build I see postgresql 10.6 and in pod container I see postgresql 10.12. So looks like we do have builds that are affected by the above CVEs.

**Comment by Fryguy** [comment]
cc @simaishi .  We probably should be building out container-postgresql a bit more frequently.

**Comment by simaishi** [comment]
manageiq/postgresql image gets auto-rebuilt when a new centos postgresql image (centos/postgresql-10-centos7) gets released. It was last rebuilt 15 days ago and contains 10.12

I don't see CVE-2020-14349 being fixed in Software Collections yet. When centos releases a new image with the fix, our postgresql image will pick that up as well.

Please note, we're using manageiq/postgresql:10 (not 'latest')

**Comment by simaishi** [comment]
We should probably delete 'latest'?

**Comment by simaishi** [comment]
As for updating images for pods, the process should be same as updating any other pods images. I don't know how pods update work or if existing instruction covers it.  cc @bdunne 

The appliance update will be same as any other rpm update (=yum update).

**Comment by bhadrim** [comment]
>>The appliance update will be same as any other rpm update (=yum update).

@simaishi Would customer need to start/stop anything before yum/rpm update of postgres or just an yum/rpm update is good enough? Thank you.

**Comment by bhadrim** [comment]
@simaishi I am not sure if yum update would work on appliance. I believe the Appstream repo from which the internal postgresql is installed do not have postgresql rpm > 10.6

[root@localhost ~]# yum list postgresql
Last metadata expiration check: 1:16:44 ago on Wed 16 Sep 2020 03:28:35 PM EDT.
Installed Packages
postgresql.x86_64          10.6-1.module_el8.0.0+15+f57f353b          @AppStream

I checked the following mirror site http://centos.mirror.rafal.ca/8.2.2004/AppStream/x86_64/os/Packages/ and I do not see any postgresql rpm > 10.6
 
[ ]	postgresql-9.6.10-1.module_el8.0.0+16+7a9f6089.x86_64.rpm	2019-07-30 19:03 	1.4M	 
[ ]	postgresql-10.6-1.module_el8.0.0+15+f57f353b.x86_64.rpm	2019-07-30 21:45 	1.5M	 
[ ]	postgresql-12.1-2.module_el8.1.0+273+979c16e6.x86_64.rpm	2020-02-05 17:46 	1.4M	 

Do you think we should add a different repo (say https://download.postgresql.org/pub/repos/yum/10/redhat/rhel-$releasever-$basearch), erase the existing rpm and use postgresql10 rpms from newer repo?

**Comment by simaishi** [comment]
I see Red Hat has released 10.14 on Sep 8 (that's 10.6 -> 10.14 update), but that hasn't been released in CentOS yet. So we have to wait for the release on CentOS side... We have never taken postgresql rpm from postgresql.org and I don't really know the difference between what's released there vs what's released in RHEL/CentOS. Unless someone familiar with postgresql can check and make sure everything still works, we won't be able to add that repo.

To clarify... appliance takes postgresql from CentOS AppStream.  The podified image uses SCL postgresql image. That's why one might be on a newer version than the other - they're on different release cycles.

**Comment by simaishi** [comment]
As for updating rpms, package owning the services should start/stop affected services on update.

**Comment by bhadrim** [comment]
> So we have to wait for the release on CentOS side

@simaishi Do you think the AppStream is being updated? I do not see anything after 10.6 on AppStream for 10.x The other repos like postgresql.org and SCL (http://mirror.centos.org/centos/7/sclo/x86_64/rh/Packages/r/) have later builds.

**Comment by simaishi** [comment]
RHEL is the upstream for CentOS, so CentOS AppStream will be updated. I'm just not sure how soon after RHEL releases a new version...

**Comment by simaishi** [comment]
@bhadrim FYI, 10.14 is available in CentOS AppStream repo: http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/

**Comment by bhadrim** [comment]
@simaishi Thank you. I will try a yum update on appliance.

**Comment by simaishi** [comment]
@bhadrim Is there anything still outstanding for this issue?

**Comment by bhadrim** [comment]
No, Thank you.
