### ISSUE TITLE
[Podified] Upgrades: handle updates to CRs with new CRD settings

### ISSUE THREAD

**Issue by jrafanie** [ManageIQ/manageiq-pods#676]
Problem:  If we adopt new default values for the cpu or memory limit/request or nearly any value we have defined the [CRD](https://github.com/ManageIQ/manageiq-pods/blob/89efdbe14731a17b4eb33777725d9562aa5fac44/manageiq-operator/deploy/crds/manageiq.org_manageiqs_crd.yaml#L31-L276) for a pod, an upgrade will not update these values in an existing CR.

@bdunne has brainstormed something like database migrations for handling values from initial installation, users and upgrades.

**Comment by Fryguy** [comment]
:+1: for migrations.  @bdunne Do you have a design?  If not, let's build one here.

**Comment by bdunne** [comment]
My thought was to copy Rails database migrations.  We would use timestamped migrations and we would have to store the list of "migrations ran" on the CR.  Then at operator startup, the first thing it would do is upgrade the CR using any migrations that have not yet been run.  Timestamped migrations would allow for downstream code injection.  Also, migrations would have to know any previous default values in order to selectively update fields without overwriting any customer values.

**Comment by Fryguy** [comment]
I'm assuming we would store the migrations_ran in the CR's status as opposed to spec?
