### ISSUE TITLE
SAML authentication with Azure AD does not work 

### ISSUE THREAD

**Issue by rabah-beldi** [ManageIQ/manageiq-pods#782]
I am trying to configure SAML authentication with Azure AD but it does not work. 
Has anyone been successful in setting up SAML authentication with Azure AD? 

FYI: I have followed the procedure: https://www.manageiq.org/docs/reference/latest/auth/saml.html

-  group created in the appliance
-  remote user parameters created on Azure AD

I got the following error when a change "MellonUser                    username" by "MellonUser        USER_ID" on the apache conf:

 INFO -- evm: MIQ(MiqAeEngine.deliver) Delivering {:event_type=>"login_failed", :event=>"authorize", :userid=>"xxxx.xxxx", :message=>"Authentication failed for userid xxxx.xxxx, unable to match user's group membership to an EVM role", "MiqEvent::miq_event"=>119531

With the conf "MellonUser                    username"  I got the following error 👍 

[auth_mellon:notice] [pid 20:tid 140690745407232] [client 10.228.16.221:34582] Didn't find the attribute "username" in the attributes which were received from the IdP. Cannot set a user for this request without a valid user attribute., referer: https://login.microsoftonline.com/

Thank you in advance for your help.

- ManageIQ version: Kasparov-1
- Minikube/KIND/OCP/CRC version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

@miq-bot add-label bug

**Comment by Fryguy** [comment]
I'm not familiar with Azure AD, but by the name it sounds more like an Active Directory interface than SAML.  Have you tried following https://www.manageiq.org/docs/reference/latest/auth/active_directory.html ?

**Comment by Fryguy** [comment]
Also if it helps there are a number of blog posts here regarding troubling shooting auth issues (in general): https://www.manageiq.org/blog/tags/tutorials/

**Comment by rabah-beldi** [comment]
Hello Fryguy ,

thank you for your quick feedback. I manage to configure AD  authentication https://www.manageiq.org/docs/reference/latest/auth/active_directory.html  on a VM. However, I can't get it to work on the podified  platform. I have already consulted the  troubling shooting page without success. Hence my issue :).

Is SSSD compatible with containers?

**Comment by Fryguy** [comment]
> Is SSSD compatible with containers?

Not exactly, no, as it requires privileged containers.  To handle that, we've created 2 different httpd containers (The httpd container is where most of the auth magic happens, and sits between the external route and the UI/API containers).

- [httpd-init](https://github.com/ManageIQ/container-httpd-init) container is basically the same thing that is in appliances.  It runs under systemd (thus needing privileged), because sssd requires systemd.  This container can handle any of the auth mechanisms we support.
- [httpd](https://github.com/ManageIQ/container-httpd) container is a different container that runs httpd _not_ under systemd.  As such, it cannot support any of the protocols that need SSSD.  So, it only support OIDC and SAML at the moment.  However, because it doesn't have systemd, it also does not need to be run as privileged.

By default we use the httpd container so as not to force users into a position where they require the less-secure model of privileged. A huge portion of users use OIDC or SAML, so this was an acceptable compromise for the default.

So, you have 2 choices.  You can switch to a SAML/OIDC backend and use the default httpd.  Or you can switch to httpd-init.  Offhand I can't remember how to do the latter, but I believe there is a way through the operator CR to do that.  @bdunne Can probably point you to the documentation or explain how to do that.

**Comment by rabah-beldi** [comment]
Hello @Fryguy ,

thanks for the precisions. I will try to configure AD authentication with the httpd-init container . 
@bdunne Do you have more information about the deployment ?

Thanks in advance.

Regards

**Comment by Fryguy** [comment]
@rabah-beldi Glad to hear you are making some progress.  Are you able to share your build / changes with us, perhaps in a pull request to httpd-init, so we can learn from it?

**Comment by bdunne** [comment]
You'll need to run https://github.com/ManageIQ/httpd_configmap_generator to use the stock httpd-init container.

**Comment by willryals-typefi** [comment]
AD isn't an option in some scenarios, for ours we use MFA through AAD SAML. So far, with the stock configuration and AAD IDP Metadata.xml, I get complaints from Lasso about it not being a valid XML document, and then when taking the relevant information and placing it into a more lasso friendly metadata xml, it results in a 500 server error after authenticating.
